name: DevSecOps Pipeline - Trivy

# This triggers the pipeline every time you push to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      # 1. Pull your code into the GitHub runner
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarqube-scan-action@v6 # Updated to v6 as per their docs
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
           -Dsonar.projectKey=${{ secrets.sonar_project_key }}
           -Dsonar.buildString=${{ github.run_id }}

      # 2. Build your FastAPI Docker image (just like you did locally)
      - name: Build Docker Image
        run: docker build -t vuln_app:latest .  

      # 3. Run Trivy and output the results as a JSON file
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'vuln_app:latest'
          format: 'json'
          output: 'trivy-results.json'
          ignore-unfixed: false
          severity: 'LOW,MEDIUM,CRITICAL,HIGH'

      # 5. Inject Pipeline Metadata
      - name: Add Pipeline Metadata to Trivy JSON
        run: |
          jq \
            --arg run_id "$GITHUB_RUN_ID" \
            --arg run_number "$GITHUB_RUN_NUMBER" \
            --arg workflow "$GITHUB_WORKFLOW" \
            --arg repo "$GITHUB_REPOSITORY" \
            --arg branch "$GITHUB_REF_NAME" \
            --arg commit_sha "$GITHUB_SHA" \
            --arg actor "$GITHUB_ACTOR" \
            '. + {
              pipeline: {
                run_id: $run_id,
                run_number: $run_number,
                workflow: $workflow,
                repo: $repo,
                branch: $branch,
                commit_sha: $commit_sha,
                actor: $actor
              },
              scan_type: "trivy"
            }' trivy-results.json > final-trivy.json

      # 5. The Magic Handoff: Send the file to your local backend
      - name: Stream Results to Local Backend
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d @final-trivy.json \
          ${{ secrets.BACKEND_URL }}
